ARG PY_VERSION=latest
FROM cpython-lldb:${PY_VERSION}

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y lldb-10 python3-lldb-10 && \
    ln -s /usr/bin/lldb-10 /usr/bin/lldb

ENV PYTHONPATH /usr/lib/llvm-10/lib/python3/dist-packages
RUN python -m pip install --target=$PYTHONPATH six
