ARG PY_VERSION=latest
FROM cpython-lldb:${PY_VERSION}

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-7 main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y lldb-7 && \
    ln -s /usr/bin/lldb-7 /usr/bin/lldb
