ARG PY_VERSION=latest
FROM python:${PY_VERSION}

COPY . /root/.lldb/cpython-lldb
RUN cd /root/.lldb/cpython-lldb && \
    python -m pip install "poetry>=0.12,<0.13" && \
    poetry install && poetry build -n -f wheel && \
    python -m pip install dist/*.whl && rm -rf dist && \
    echo "command script import cpython_lldb" >> /root/.lldbinit && \
    chmod +x /root/.lldbinit

CMD ["/usr/bin/lldb"]
